export type GithubData = {
  data: {
    name: string;
    username: string;
    year: number;
    avatar: string;
    total_contributions: number;
    contribution_percentile: number;
    global_contributions: number;
    contribution_streak: number;
    commit_history: {
      january: number;
      february: number;
      march: number;
      april: number;
      may: number;
      june: number;
      july: number;
      august: number;
      september: number;
      october: number;
      november: number;
    };
    commits_during_day: number;
    total_commits: number;
    frequent_reviewers_and_reviewees: string[];
    prs_with_revert: number;
    reviewed_prs_not_reverted: number;
    frequent_reviewers: string[];
    reviewer_lag: number;
    reviewee_lag: number;
    authored_prs: number;
    reviewed_prs: number;
    prod_breaks: number;
    oss_contributions: number;
  };
};

export type Plan = {
  name: string;
  space: number;
  collaborators: number;
  private_repos: number;
};

export type GitHubDataResponse = {
  user: {
    login: string;
    id: number;
    node_id: string;
    avatar_url: string;
    gravatar_id: string;
    url: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: string;
    received_events_url: string;
    type: string;
    site_admin: boolean;
    name: string;
    company: string;
    blog: string;
    location: string;
    email: string | null;
    hireable: boolean | null;
    bio: string;
    twitter_username: string | null;
    public_repos: number;
    public_gists: number;
    followers: number;
    following: number;
    created_at: string;
    updated_at: string;
    private_gists: number;
    total_private_repos: number;
    owned_private_repos: number;
    disk_usage: number;
    collaborators: number;
    two_factor_authentication: boolean;
    plan: Plan;
  };
  authored_monthly_pr_counts: number[];
  reviewed_monthly_pr_counts: number[];
  total_contributions: number;
  total_additions: number;
  total_deletions: number;
  top_reviewed_contributors: string[];
  top_reviewers: string[];
  monthly_contributions: { [key: string]: number };
  longest_streak: number;
  total_oss_contributions: number;
  prs_opened_during_day: number;
  prs_opened_during_night: number;
  contribution_percentile: number;
  global_contributions: number;
};
